language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
before_install:
  - "npm install -g gulp"
  - "npm install -g coveralls"
script:
  - "npm test"
after_success:
  - "npm run coveralls"
