language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
before_install:
  - "npm install -g npm"
  - "npm install -g gulp"
  - "npm install -g bower"
  - "npm install -g coveralls"
before_script:
  - "npm run-script bower"
script:
  - "npm test"
after_success:
  - "npm run-script coveralls"
